---
- name: Install Damn Vulnerable Web Application (DVWA)
  hosts: dvwa
  become: true

  tasks:
    - name: Enable EPEL Repository on AlmaLinux 9
      ansible.builtin.dnf:
        name:
          - epel-release
        state: present

    - name: Install dependencies
      ansible.builtin.dnf:
        name:
          - git
          - httpd
          - mariadb
          - mariadb-server
          - php
          - php-common
          - php-gd
          - php-mysqlnd
          - python39
          - python3-mysqlclient
        state: present

    - name: Run httpd
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started

    - name: Run mariadb
      ansible.builtin.service:
        name: mariadb
        enabled: true
        state: started

    - name: Clone DVWA
      ansible.builtin.git:
        repo: "https://github.com/digininja/DVWA.git"
        dest: /var/www/html/
        version: 32d372521df7f4908c13d6718f4f49897f248e5c
        update: false

    - name: Disable SELinux
      ansible.posix.selinux:
        state: disabled

    - name: Create DVWA config
      ansible.builtin.copy:
        src: /var/www/html/config/config.inc.php.dist
        dest: /var/www/html/config/config.inc.php
        owner: apache
        group: apache
        mode: "0644"
        remote_src: true

    - name: Update php.ini file
      ansible.builtin.replace:
        path: "/etc/php.ini"
        regexp: "allow_url_include = .*"
        replace: "allow_url_include = On"
        backup: true
      notify:
        - Restart httpd
        - Restart php-fpm

    - name: Update owner
      ansible.builtin.file:
        dest: /var/www/html
        owner: apache
        group: root
        recurse: true

    - name: Create 'dvwa' database
      community.mysql.mysql_db:
        name: "dvwa"
        state: present
      notify: Restart mariadb

    - name: Create user and grant privileges
      community.mysql.mysql_user:
        name: "dvwa"
        password: "p@ssw0rd"
        priv: "dvwa.*:ALL,GRANT"
        state: present
      notify: Restart mariadb

    - name: Disable Firewall
      ansible.builtin.service:
        name: firewalld
        state: stopped

  handlers:
    - name: Restart httpd
      ansible.builtin.service:
        name: httpd
        state: restarted

    - name: Restart php-fpm
      ansible.builtin.service:
        name: php-fpm
        state: restarted

    - name: Restart mariadb
      ansible.builtin.service:
        name: mariadb
        state: restarted
